# -*- coding: utf-8 -*-
import json, sys
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8')

T = {
'3-4-sit-up':'3/4卷腹','arms-overhead-full-sit-up-male':'过顶全幅卷腹','assisted-hanging-knee-raise':'辅助悬垂屈膝举腿',
'assisted-hanging-knee-raise-with-throw-down':'辅助悬垂屈膝下抛','assisted-parallel-close-grip-pull-up':'辅助对握窄引体',
'assisted-prone-rectus-femoris-stretch':'辅助俯卧股直肌拉伸','assisted-seated-pectoralis-major-stretch-with-stability-ball':'辅助球上胸大肌拉伸',
'assisted-sit-up':'辅助卷腹','assisted-standing-chin-up':'辅助站姿反手引体','back-lever':'后水平','backward-jump':'后跳',
'balance-board':'平衡板','band-alternating-v-up':'弹力带交替V字两头起','band-assisted-wheel-rollerout':'弹力带辅助健腹轮',
'band-jack-knife-sit-up':'弹力带折刀卷腹','band-push-sit-up':'弹力带推式卷腹','band-standing-rear-delt-row':'弹力带站姿后束划船',
'band-v-up':'弹力带V字两头起','barbell-clean-grip-front-squat':'翻握颈前深蹲','barbell-high-bar-squat':'高杠深蹲',
'barbell-low-bar-squat':'低杠深蹲','barbell-lying-back-of-the-head-tricep-extension':'仰卧脑后三头屈伸',
'barbell-press-sit-up':'杠铃推举卷腹','barbell-rear-delt-raise':'杠铃后束平举','barbell-rear-delt-row':'杠铃后束划船',
'barbell-revers-wrist-curl-v-2':'杠铃反腕弯举','barbell-rollerout-from-bench':'凳上杠铃健腹轮',
'barbell-seated-close-grip-behind-neck-triceps-extension':'坐姿窄握颈后三头屈伸','barbell-side-bent-v-2':'杠铃体侧屈',
'barbell-standing-front-raise-over-head':'站姿过顶前平举','barbell-thruster':'杠铃借力推举','biceps-leg-concentration-curl':'腿部集中弯举',
'biceps-narrow-pull-ups':'窄握二头引体','biceps-pull-up':'二头引体向上','body-up':'撑体起','bottoms-up':'倒壶提拉','butt-ups':'臀部起伏',
'cable-cross-over-revers-fly':'绳索交叉反向飞鸟','cable-cross-over-variation':'绳索交叉变式','cable-floor-seated-wide-grip-row':'绳索坐姿宽握划船',
'cable-high-pulley-overhead-tricep-extension':'绳索高位过顶三头屈伸','cable-kneeling-rear-delt-row-with-rope-male':'跪姿绳把后束划船',
'cable-lateral-pulldown-with-v-bar':'V把侧向下拉','cable-one-arm-lateral-bent-over':'单臂侧俯身','cable-pulldown-bicep-curl':'下拉接二头弯举',
'cable-rear-delt-row-stirrups':'绳索吊带后束划船','cable-rear-delt-row-with-rope':'绳把后束划船','cable-rear-drive':'绳索后驱',
'cable-rope-crossover-seated-row':'绳索交叉坐姿划船','cable-rope-extension-incline-bench-row':'绳索上斜凳划船',
'cable-rope-hammer-preacher-curl':'绳索锤式牧师弯举','cable-rope-high-pulley-overhead-tricep-extension':'绳索高位过顶三头屈伸',
'cable-rope-lying-on-floor-tricep-extension':'绳索地板三头屈伸','cable-rope-one-arm-hammer-preacher-curl':'绳索单臂锤式牧师弯举',
'cable-russian-twists-on-stability-ball':'球上绳索俄罗斯转体','cable-seated-shoulder-internal-rotation':'坐姿肩内旋',
'cable-side-bend-crunch-bosu-ball':'波速球侧屈卷腹','cable-squatting-curl':'蹲姿绳索弯举','cable-standing-inner-curl':'站姿内侧弯举',
'cable-standing-lift':'站姿绳索提拉','cable-standing-rear-delt-row-with-rope':'站姿绳把后束划船',
'cable-standing-shoulder-external-rotation':'站姿肩外旋','cable-standing-twist-row-v-bar':'站姿V把转体划船',
'cable-standing-up-straight-crossovers':'站姿直立交叉','cable-thibaudeau-kayak-row':'皮划艇式划船',
'cable-tuck-reverse-crunch':'绳索收膝反向卷腹','cable-twisting-pull':'绳索转体拉','cable-two-arm-tricep-kickback':'双臂三头后踢',
'cable-upper-chest-crossovers':'上胸绳索交叉','cable-upper-row':'高位划船','cable-wide-grip-rear-pulldown-behind-neck':'宽握颈后下拉',
'calf-push-stretch-with-hands-against-wall':'推墙小腿拉伸','calf-stretch-with-hands-against-wall':'扶墙小腿拉伸',
'calf-stretch-with-rope':'绳索小腿拉伸','captains-chair-straight-leg-raise':'器械直腿举腿','chair-leg-extended-stretch':'椅上伸腿拉伸',
'chest-and-front-of-shoulder-stretch':'胸肩前侧拉伸','chest-dip-on-straight-bar':'直杠胸双杠','chest-stretch-with-exercise-ball':'球上胸部拉伸',
'chest-tap-push-up-male':'拍胸俯卧撑','chin-up':'反手引体向上','chin-ups-narrow-parallel-grip':'窄对握反手引体',
'circles-knee-stretch':'绕膝拉伸','clap-push-up':'击掌俯卧撑','clock-push-up':'时钟俯卧撑','close-grip-chin-up':'窄握反手引体',
'cocoons':'蚕茧卷','crab-twist-toe-touch':'螃蟹转体摸脚','cross-body-crunch':'交叉卷腹','crunch-floor':'地板卷腹','curl-up':'卷体',
'curtsey-squat':'屈膝礼深蹲','cycle-cross-trainer':'椭圆机','dead-bug':'死虫式','decline-sit-up':'下斜卷腹','deep-push-up':'深俯卧撑',
'dumbbell-alternate-hammer-preacher-curl':'交替锤式牧师弯举','dumbbell-alternating-bicep-curl-with-leg-raised-on-exercise-ball':'球上举腿交替弯举',
'dumbbell-around-pullover':'绕环仰卧上拉','dumbbell-bicep-curl-lunge-with-bowling-motion':'保龄球式弯举箭步',
'dumbbell-bicep-curl-on-exercise-ball-with-leg-raised':'球上举腿二头弯举','dumbbell-bicep-curl-with-stork-stance':'鹳立式二头弯举',
'dumbbell-biceps-curl-reverse':'反握二头弯举','dumbbell-biceps-curl-squat':'弯举深蹲','dumbbell-biceps-curl-v-sit-on-bosu-ball':'波速球V坐弯举',
'dumbbell-contralateral-forward-lunge':'对侧前箭步','dumbbell-cross-body-hammer-curl':'交叉锤式弯举','dumbbell-cross-body-hammer-curl-v-2':'交叉锤式弯举',
'dumbbell-cuban-press':'古巴推举','dumbbell-cuban-press-v-2':'古巴推举','dumbbell-full-can-lateral-raise':'满罐侧平举',
'dumbbell-incline-breeding':'上斜哑铃扩胸','dumbbell-incline-palm-in-press':'上斜对掌卧推','dumbbell-incline-twisted-flyes':'上斜旋转飞鸟',
'dumbbell-iron-cross':'哑铃铁十字','dumbbell-kickbacks-on-exercise-ball':'球上三头后踢','dumbbell-kneeling-bicep-curl-exercise-ball':'跪姿球上弯举',
'dumbbell-lateral-to-front-raise':'侧平举接前平举','dumbbell-lunge-with-bicep-curl':'弯举箭步蹲','dumbbell-lying-external-shoulder-rotation':'仰卧肩外旋',
'dumbbell-lying-femoral':'仰卧股后弯举','dumbbell-lying-on-floor-rear-delt-raise':'地板仰卧后束平举','dumbbell-lying-one-arm-deltoid-rear':'仰卧单臂后束',
'dumbbell-lying-rear-delt-row':'仰卧后束划船','dumbbell-lying-single-extension':'仰卧单臂屈伸','dumbbell-lying-supination':'仰卧旋后',
'dumbbell-lying-supination-on-floor':'地板仰卧旋后','dumbbell-one-arm-hammer-preacher-curl':'单臂锤式牧师弯举',
'dumbbell-over-bench-neutral-wrist-curl':'凳上中立腕弯举','dumbbell-over-bench-one-arm-neutral-wrist-curl':'凳上单臂中立腕弯举',
'dumbbell-over-bench-one-arm-reverse-wrist-curl':'凳上单臂反腕弯举','dumbbell-over-bench-one-arm-wrist-curl':'凳上单臂腕弯举',
'dumbbell-over-bench-revers-wrist-curl':'凳上反腕弯举','dumbbell-over-bench-wrist-curl':'凳上腕弯举',
'dumbbell-palm-rotational-bent-over-row':'旋掌俯身划船','dumbbell-palms-in-incline-bench-press':'对掌上斜卧推',
'dumbbell-plyo-squat':'哑铃爆发深蹲','dumbbell-preacher-curl-over-exercise-ball':'球上牧师弯举','dumbbell-pronate-grip-triceps-extension':'正握三头屈伸',
'dumbbell-rear-delt-raise':'哑铃后束平举','dumbbell-rear-delt-row-shoulder':'后束肩划船','dumbbell-revers-grip-biceps-curl':'反握二头弯举',
'dumbbell-scott-press':'斯科特推举','dumbbell-seated-alternate-shoulder':'坐姿交替推肩','dumbbell-seated-bent-arm-lateral-raise':'坐姿屈臂侧平举',
'dumbbell-seated-biceps-curl-to-shoulder-press':'弯举接推肩','dumbbell-seated-one-arm-bicep-curl-on-exercise-ball-with-leg-raised':'球上举腿单臂弯举',
'dumbbell-seated-one-arm-rotate':'坐姿单臂旋转','dumbbell-seated-one-leg-calf-raise-hammer-grip':'坐姿单腿锤握提踵',
'dumbbell-seated-one-leg-calf-raise-palm-up':'坐姿单腿掌上提踵','dumbbell-seated-revers-grip-concentration-curl':'反握集中弯举',
'dumbbell-side-lying-one-hand-raise':'侧卧单手上举','dumbbell-side-plank-with-rear-fly':'侧平板反向飞鸟',
'dumbbell-single-leg-deadlift-with-stepbox-support':'箱支撑单腿硬拉','dumbbell-standing-alternate-hammer-curl-and-press':'交替锤弯接推举',
'dumbbell-standing-alternating-tricep-kickback':'站姿交替三头后踢','dumbbell-standing-around-world':'环绕世界平举',
'dumbbell-standing-front-raise-above-head':'过顶前平举','dumbbell-standing-one-arm-curl-over-incline-bench-2':'上斜凳单臂弯举',
'dumbbell-standing-one-arm-palm-in-press':'单臂对掌推举','dumbbell-standing-palms-in-press':'对掌推举',
'dumbbell-step-up-single-leg-balance-with-bicep-curl':'登阶平衡弯举','dumbbell-step-up-lunge':'登阶箭步','dumbbell-step-up-split-squat':'登阶分腿蹲',
'dumbbell-supported-squat':'支撑深蹲','dumbbell-tate-press':'泰特推举','dumbbell-tricep-kickback-with-stork-stance':'鹳立三头后踢',
'dumbbell-upright-shoulder-external-rotation':'直立肩外旋','dumbbell-waiter-biceps-curl':'侍者弯举','dumbbell-w-press':'W形推举',
'dumbbells-seated-triceps-extension':'坐姿三头屈伸','dynamic-chest-stretch-male':'动态胸部拉伸','elbow-dips':'肘撑臂屈伸',
'elbow-lift-reverse-push-up':'肘撑反向俯卧撑','elbow-to-knee':'肘碰膝','elevator':'电梯式引体',
'exercise-ball-alternating-arm-ups':'球上交替抬臂','exercise-ball-back-extension-with-arms-extended':'球上直臂挺身',
'exercise-ball-back-extension-with-hands-behind-head':'球上抱头挺身','exercise-ball-back-extension-with-knees-off-ground':'球上悬膝挺身',
'exercise-ball-back-extension-with-rotation':'球上旋转挺身','exercise-ball-hug':'抱球挤压','exercise-ball-lower-back-stretch-pyramid':'球上下背金字塔',
'exercise-ball-lying-side-lat-stretch':'球上侧卧背阔拉伸','exercise-ball-on-the-wall-calf-raise':'靠墙球上提踵',
'exercise-ball-on-the-wall-calf-raise-tennis-ball-between-ankles':'夹球靠墙提踵','exercise-ball-on-the-wall-calf-raise-tennis-ball-between-knees':'膝夹球提踵',
'exercise-ball-one-leg-prone-lower-body-rotation':'球上单腿俯卧转体','exercise-ball-seated-hamstring-stretch':'球上坐姿腘绳拉伸',
'ez-bar-lying-bent-arms-pullover':'曲杆仰卧屈臂上拉','ez-barbell-decline-close-grip-face-press':'下斜窄握面推',
'farmers-walk':'农夫行走','flexion-leg-sit-up-bent-knee':'屈膝卷腹','flexion-leg-sit-up-straight-arm':'直臂卷腹',
'flutter-kicks':'仰卧打腿','frankenstein-squat':'科学怪人深蹲','frog-crunch':'蛙式卷腹','frog-planche':'蛙式平板',
'front-lever':'前水平','front-lever-reps':'前水平反复','full-maltese':'全马尔他支撑','full-planche':'全平板支撑',
'full-planche-push-up':'全平板俯卧撑','gironda-sternum-chin':'胸骨反手引体','glute-ham-raise':'腘绳臀肌挺身',
'gorilla-chin':'大猩猩引体','groin-crunch':'腹股沟卷腹','half-knee-bends-male':'半蹲','half-sit-up-male':'半程卷腹',
'hands-bike':'手摇功率车','hands-clasped-circular-toe-touch-male':'握手绕环摸脚','hands-reversed-clasped-circular-toe-touch-male':'反握绕环摸脚',
'handstand':'靠墙倒立','handstand-push-up':'倒立撑','hanging-leg-hip-raise':'悬垂举腿髋','hanging-oblique-knee-raise':'悬垂腹斜屈膝',
'hanging-straight-twisting-leg-hip-raise':'悬垂直腿转体举','high-knee-against-wall':'靠墙高抬腿','hug-keens-to-chest':'抱膝贴胸',
'hyght-dumbbell-fly':'海格特哑铃飞鸟','impossible-dips':'极限臂屈伸','inchworm':'尺蠖爬行','inchworm-v-2':'尺蠖爬行',
'incline-leg-hip-raise-leg-straight':'上斜直腿髋举','incline-push-up-depth-jump':'上斜俯卧撑跳深','incline-scapula-push-up':'上斜肩胛俯卧撑',
'incline-twisting-sit-up':'上斜转体卷腹','intermediate-hip-flexor-and-quad-stretch':'髋屈肌股四头拉伸',
'inverted-row-with-straps':'吊带反向划船','iron-cross-stretch':'铁十字拉伸','isometric-chest-squeeze':'静态夹胸','isometric-wipers':'静态雨刷式',
'jack-burpee':'开合波比','jack-jump-male':'开合跳','jackknife-sit-up':'折刀卷腹','janda-sit-up':'扬达卷腹','jump-rope':'跳绳',
'kettlebell-advanced-windmill':'高阶壶铃风车','kettlebell-alternating-renegade-row':'交替叛徒划船','kettlebell-bent-press':'壶铃弯身推举',
'kettlebell-bottoms-up-clean-from-the-hang-position':'倒壶悬垂翻','kettlebell-double-alternating-hang-clean':'双壶交替悬垂翻',
'kettlebell-double-jerk':'双壶挺举','kettlebell-double-push-press':'双壶借力推','kettlebell-double-snatch':'双壶抓举',
'kettlebell-double-windmill':'双壶风车','kettlebell-extended-range-one-arm-press-on-floor':'地板单臂延伸推举',
'kettlebell-figure-8':'壶铃8字绕','kettlebell-lunge-pass-through':'箭步穿铃','kettlebell-one-arm-clean-and-jerk':'单臂挺举',
'kettlebell-one-arm-jerk':'单壶挺举','kettlebell-one-arm-military-press-to-the-side':'单臂侧向实力推',
'kettlebell-pirate-supper-legs':'海盗船式','kettlebell-plyo-push-up':'壶铃爆发俯卧撑','kettlebell-seesaw-press':'跷跷板推举',
'kettlebell-sumo-high-pull':'相扑高拉','kettlebell-thruster':'壶铃借力推举','kettlebell-turkish-get-up-squat-style':'蹲式土耳其起立',
'kettlebell-windmill':'壶铃风车','kick-out-sit':'踢出坐起','kipping-muscle-up':'借力双力臂','knee-touch-crunch':'碰膝卷腹',
'kneeling-plank-tap-shoulder-male':'跪姿平板拍肩','korean-dips':'韩式臂屈伸','l-pull-up':'L形引体','l-sit-on-floor':'地板L支撑',
'lean-planche':'平板前倾','left-hook-boxing':'左勾拳','leg-pull-in-flat-bench':'平凳收腿',
'lever-alternating-narrow-grip-seated-row':'交替窄握坐姿划船','lever-assisted-chin-up':'器械辅助反手引体',
'lever-bent-over-row-with-v-bar':'V把俯身划船','lever-gripless-shrug':'无握耸肩','lever-gripless-shrug-v-2':'无握耸肩',
'lever-gripper-hands':'握力器训练','lever-hammer-grip-preacher-curl':'锤握牧师弯举','lever-lying-two-one-leg-curl':'俯卧单腿弯举',
'lever-narrow-grip-seated-row':'窄握坐姿划船','lever-rotary-calf':'旋转提踵器','lever-seated-calf-press':'坐姿小腿推',
'lever-seated-leg-raise-crunch':'坐姿举腿卷腹','lever-t-bar-reverse-grip-row':'反握T杠划船','lever-unilateral-row':'单侧划船',
'lunge-with-jump':'跳跃箭步蹲','lying-elbow-to-knee':'仰卧肘碰膝','lying-leg-hip-raise':'仰卧举腿髋',
'machine-inner-chest-press':'内侧推胸器','march-sit-wall':'靠墙静蹲踏步','medicine-ball-catch-and-overhead-throw':'药球接抛过顶',
'medicine-ball-chest-pass':'药球胸前传球','medicine-ball-chest-push-with-run-release':'药球跑动前推',
'medicine-ball-overhead-slam':'药球过顶砸','medicine-ball-supine-chest-throw':'仰卧药球胸前抛','mixed-grip-chin-up':'混合握反手引体',
'modified-hindu-push-up-male':'改良印度俯卧撑','modified-push-up-to-lower-arms':'前臂降阶俯卧撑','monster-walk':'怪兽行走',
'neck-side-stretch':'颈部侧向拉伸','oblique-crunch-v-2':'腹斜肌卷腹','oblique-crunches-floor':'地板腹斜卷腹',
'one-arm-against-wall':'单臂靠墙撑','one-arm-chin-up':'单臂反手引体','one-arm-slam-with-medicine-ball':'单臂药球砸',
'otis-up':'奥蒂斯起坐','outside-leg-kick-push-up':'外侧踢腿俯卧撑','peroneals-stretch':'腓骨肌拉伸',
'pike-to-cobra-push-up':'折刀接眼镜蛇俯卧撑','plyo-push-up':'爆发俯卧撑','posterior-step-to-overhead-reach':'后踏过顶伸展',
'potty-squat':'马桶蹲','potty-squat-with-support':'支撑马桶蹲','power-point-plank':'能量点平板','prisoner-half-sit-up-male':'囚犯半卷腹',
'prone-twist-on-stability-ball':'球上俯卧转体','pull-in-on-stability-ball':'球上收膝','push-and-pull-bodyweight':'自重推拉组合',
'push-to-run':'推墙跑','push-up-close-grip-off-dumbbell':'哑铃窄距俯卧撑','push-up-inside-leg-kick':'内侧踢腿俯卧撑',
'push-up-medicine-ball':'药球俯卧撑','push-up-on-lower-arms':'前臂俯卧撑','push-up-plus':'俯卧撑加强版',
'push-up-to-side-plank':'俯卧撑接侧平板','quads':'股四头肌拉伸','quarter-sit-up':'四分之一卷腹','quick-feet-v-2':'快速碎步',
'raise-single-arm-push-up':'举臂单侧俯卧撑','rear-decline-bridge':'下斜背桥','rear-deltoid-stretch':'三角肌后束拉伸',
'reclining-big-toe-pose-with-rope':'仰卧大脚趾式','resistance-band-hip-thrusts-on-knees-female':'跪姿弹力带臀推',
'reverse-grip-machine-lat-pulldown':'反握高位下拉','reverse-hyper-extension-on-stability-ball':'球上反向挺身',
'reverse-hyper-on-flat-bench':'平凳反向挺身','reverse-plank-with-leg-lift':'反向平板抬腿','ring-dips':'吊环臂屈伸',
'rocking-frog-stretch':'摇摆蛙式拉伸','rocky-pull-up-pulldown':'洛奇引体下拉','roller-body-saw':'滚轴身体锯',
'roller-hip-lat-stretch':'滚轴髋背阔拉伸','roller-hip-stretch':'滚轴髋部拉伸','roller-side-lat-stretch':'滚轴侧背拉伸',
'rope-climb':'爬绳','runners-stretch':'跑者拉伸','scapula-dips':'肩胛双杠','scapula-push-up':'肩胛俯卧撑',
'scapular-pull-up':'肩胛引体','scissor-jumps-male':'剪刀跳','seated-calf-stretch-male':'坐姿小腿拉伸',
'seated-lower-back-stretch':'坐姿下背拉伸','seated-piriformis-stretch':'坐姿梨状肌拉伸','seated-wide-angle-pose-sequence':'坐角式序列',
'semi-squat-jump-male':'半蹲跳','short-stride-run':'小步快跑','shoulder-grip-pull-up':'抓肩引体','shoulder-tap':'站姿拍肩',
'shoulder-tap-push-up':'拍肩俯卧撑','side-bridge-hip-abduction':'侧桥髋外展','side-bridge-v-2':'侧桥',
'side-hip-on-parallel-bars':'双杠侧髋','side-lying-floor-stretch':'侧卧地板拉伸','side-plank-hip-adduction':'侧平板髋内收',
'side-push-neck-stretch':'侧推颈拉伸','side-wrist-pull-stretch':'侧腕牵拉','side-to-side-chin':'左右反手引体',
'side-to-side-toe-touch-male':'左右摸脚','single-leg-bridge-with-outstretched-leg':'单腿伸直臀桥',
'single-leg-platform-slide':'单腿平台滑步','sit-up-v-2':'卷腹','sit-up-with-arms-on-chest':'抱胸卷腹',
'skater-hops':'滑冰跳','ski-ergometer':'滑雪机','ski-step':'滑雪步','skin-the-cat':'猫式翻转',
'sled-45-degrees-one-leg-press':'45度单腿倒蹬','sled-45-calf-press':'45度小腿推','sled-45-leg-press':'45度倒蹬',
'sled-45-leg-press-back-pov':'45度倒蹬','sled-45-leg-press-side-pov':'45度倒蹬','sled-45-leg-wide-press':'45度宽距倒蹬',
'sled-calf-press-on-leg-press':'倒蹬机提踵','sled-closer-hack-squat':'窄站哈克蹲','sled-forward-angled-calf-raise':'前倾提踵',
'sled-hack-squat':'哈克深蹲','sled-lying-calf-press':'仰卧小腿推','sled-lying-squat':'仰卧深蹲',
'sled-one-leg-calf-press-on-leg-press':'单腿倒蹬提踵','sledge-hammer':'挥大锤','smith-bent-knee-good-morning':'史密斯屈膝早安',
'smith-low-bar-squat':'史密斯低杠蹲','smith-rear-delt-row':'史密斯后束划船','smith-sprint-lunge':'史密斯冲刺箭步',
'smith-toe-raise':'史密斯提踵','snatch-pull':'抓举硬拉','spell-caster':'拼字者转体','sphinx':'斯芬克斯式',
'spider-crawl-push-up':'蜘蛛爬俯卧撑','spine-stretch':'脊柱拉伸','spine-twist':'脊柱扭转','squat-jerk':'深蹲挺举',
'squat-to-overhead-reach':'深蹲过顶伸展','squat-to-overhead-reach-with-twist':'深蹲转体过顶伸展',
'stalder-press':'斯塔尔德推','standing-archer':'站姿弓箭手','standing-calves':'站姿提踵',
'standing-hamstring-and-calf-stretch-with-strap':'站姿腘绳小腿拉伸','star-jump-male':'星形跳','stationary-bike-walk':'动感单车慢骑',
'straddle-maltese':'分腿马尔他','straddle-planche':'分腿平板','straight-leg-outer-hip-abductor':'直腿髋外展',
'superman-push-up':'超人俯卧撑','suspended-abdominal-fallout':'悬吊腹肌展开','suspended-push-up':'悬吊俯卧撑',
'suspended-reverse-crunch':'悬吊反向卷腹','suspended-row':'悬吊划船','suspended-split-squat':'悬吊分腿蹲',
'swimmer-kicks-v-2-male':'游泳打腿','three-bench-dip':'三凳臂屈伸','tire-flip':'翻轮胎','triceps-dips-floor':'地板三头屈伸',
'triceps-press':'三头推','tuck-crunch':'收膝卷腹','twin-handle-parallel-grip-lat-pulldown':'对握高位下拉',
'twist-hip-lift':'转体髋提','twisted-leg-raise':'转体举腿','twisted-leg-raise-female':'转体举腿',
'two-toe-touch-male':'双摸脚尖','upper-back-stretch':'上背拉伸','upward-facing-dog':'上犬式','v-sit-on-floor':'地板V字支撑',
'walk-elliptical-cross-trainer':'椭圆机行走','walking-high-knees-lunge':'高抬腿箭步走','walking-on-incline-treadmill':'坡度快走',
'walking-on-stepmill':'爬楼梯机','weighted-close-grip-chin-up-on-dip-cage':'负重窄握反手引体','weighted-decline-sit-up':'负重下斜卷腹',
'weighted-hanging-leg-hip-raise':'负重悬垂举腿','weighted-kneeling-step-with-swing':'跪姿负铃摆腿','weighted-lunge-with-swing':'负铃摆动箭步',
'weighted-one-hand-pull-up':'负重单手引体','weighted-round-arm':'负重绕臂','weighted-standing-hand-squeeze':'负重握力挤压',
'weighted-straight-bar-dip':'负重直杠双杠','weighted-svend-press':'斯文德夹胸推','weighted-three-bench-dips':'负重三凳双杠',
'weighted-tricep-dips':'负重三头双杠','weighted-triceps-dip-on-high-parallel-bars':'高双杠负重三头','wheel-run':'滚轮跑',
'wide-hand-push-up':'宽距俯卧撑','wide-grip-chest-dip-on-high-parallel-bars':'高双杠宽握胸双杠','wind-sprints':'冲刺跑',
'wrist-rollerer':'腕部滚轴',
}

P = Path('src/data/manifest.json')
m = json.loads(P.read_text(encoding='utf-8'))
applied, miss = 0, []
for o in m:
    if o['zh'] == o['name'] and o['slug'] in T:
        o['zh'] = T[o['slug']]
        applied += 1
P.write_text(json.dumps(m, ensure_ascii=False), encoding='utf-8')
remain = [o['slug'] for o in m if o['zh'] == o['name']]
print(f'应用: {applied} | 剩余英文: {len(remain)}')
print('漏网:', remain[:20])
